api_key_lat_lon=https://api.openweathermap.org/data/2.5/weather?lat=%.5f&lon=%.5f&appid=d5c6861bc694bf12e0d19183e6e07195
api_key_filter=https://api.openweathermap.org/geo/1.0/direct?q=%s&limit=10&appid=d5c6861bc694bf12e0d19183e6e07195
